################### WebSite\uFF1Ahttps://www.fuint.cn #########################
# \u5B9A\u65F6\u53D1\u9001\u6D88\u606F
message.job.switch = 0
message.job.time = 0 0/1 * * * ?

# \u5361\u5238\u5230\u671F\u5904\u7406
couponExpire.job.switch = 0
couponExpire.job.time = 0 0/1 * * * ?

# \u8BA2\u5355\u8D85\u65F6\u53D6\u6D88
orderCancel.job.switch = 0
orderCancel.job.time = 0 0/1 * * * ?

# \u5206\u4F63\u63D0\u6210\u8BA1\u7B97
commission.job.switch = 1
commission.job.time = 0 0/1 * * * ?

# \u5FAE\u4FE1\u5C0F\u7A0B\u5E8F\u4E0A\u4F20\u53D1\u8D27\u4FE1\u606F\u5904\u7406
uploadShippingInfoJob.job.switch = 1
uploadShippingInfoJob.job.time = 0 0/1 * * * ?
